#56 Gestion du back button d'android : on ferme l'application si on se situe sur la homepage
andritiana/stkNationaly pull request #57
Opened 2022-04-30 15:45 UTC by haryratsimba

2022-10-09 20:01 UTC, haryratsimba commented
Hello @hearoy est-ce que tu pourras retester stp ? J'ai réadapté le fix suite à l'ajout du profile de la RNSTK.
Merci pour test tests :D

2022-10-11 16:32 UTC, hearoy requested changes
Ça marche bien 👏🏽

2022-10-11 16:32 UTC, hearoy commented on src/app/app.component.ts
> +      if (url === '/tabs/home') {
Ah oui, j'avais oublié que ça avait changé 😅 bien vu !

On peut ajouter un commentaire sur la route correspondante dans `tabs-routing.module.ts` pour prévenir qu'elle est utilisée ici pour le back button ?  À défaut de/en attendant les tests, ça nous fera un petit pour quand les routes changeront.

2022-10-11 17:15 UTC, haryratsimba commented on src/app/app.component.ts
> +      if (url === '/tabs/home') {
Merci pour les tests ;)
J'ai rajouté le commentaire. Je demande dans le groupe si on peut passer ce ticket avec la release de jeudi si ça te va aussi ;)

2022-10-11 17:44 UTC, hearoy approved these changes

2022-10-11 20:38 UTC, merged