#58 Création d'un service permettant d'autoriser et afficher correctement les iframe pour Youtube et Soundcloud
andritiana/stkNationaly pull request #92
Opened 2022-07-20 20:29 UTC by haryratsimba

2022-09-30 23:13 UTC, hearoy commented
J'ai rebase sur develop.

2022-10-01 09:24 UTC, hearoy requested changes

2022-10-01 09:24 UTC, hearoy commented
J'ai testé et ça marche bien ! 👍🏽

2022-10-01 13:12 UTC, haryratsimba commented on src/app/services/player-service.ts
> +    public enablePlayableEmbededContent(htmlContent: string): SafeHtml {
Merci pour les retours ! J'aime bien l'idée du pipe ! Si ça te va, je te laisse modifier pour implémenter cette idée ? Je t'avoue que je suis un peu limité en Angular 😅
Merci en tout cas !

2022-10-04 20:23 UTC, haryratsimba commented
Désolé j'ai fais un merge foireux (ça a restauré le code inutilisé), j'ai remis comme tu as fais dans le commit [23f93eb](https://github.com/andritiana/stkNationaly/pull/92/commits/23f93eba0abac2232c7a5b35ef71181bd916ebd8)
Testé sur navigateur ça marche très bien merci !

2022-10-04 21:49 UTC, hearoy commented on src/app/services/player-service.ts
> +    public enablePlayableEmbededContent(htmlContent: string): SafeHtml {
Refacto dans un component.

2022-10-04 21:50 UTC, hearoy commented on src/app/services/player-service.ts
> +        container.innerHTML = htmlContent;
👌🏽

2022-10-09 15:19 UTC, hearoy approved these changes

2022-10-09 17:35 UTC, merged